config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'sessions/new'

  get 'user/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'signup' => 'users#new'

  resources :posts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

   root 'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

app/views/shared/_feed.html.erb
 <% if @feed_items.any? %>
 <ol class="posts">
  <%= render @feed_items %>
 </ol>
 <%= will_paginate @feed_items %>
 <% end %>

app/views/shared/_foot.html.erb
<div class="center jumbotron">
	<h1>Welcome to the sample app</h1>

	<h2>
		this is the home page for the <%= link_to "Rails toturial", 'http://rail.org' %>
	</h2>

	<%= link_to "sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "rails logo"),'http:ok.org' %>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
 <%= f.text_area :content, placeholder: "Conpose new post..." %>
 </div>
 <%= f.submit "Post", class: "btn btn-primary" %>
 <span class = "picture">
 <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
 </span>
 <% end %>

 <script type="text/javascrpt">
  $('#post_picture').bind('change', function(){
  	var size_in_megabytes = this.files[0].size/1024/1024;
  	if(size_in_megabytes >5){
  		alert('Max file size is 5MB. please choose a smaller file.');
  	}
  });
  </script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
 <a href="<%= following_user_path(@user)%>">
  <strong id="following" class="stats">
   <%= @user.following.count %>
   </strong>
   following
   </a>
   <a href="<%= followers_user_path(@user)%>">
    <strong id="follower" class="stats">
     <%= @user.followers.count %>
     </strong>
    followers
   </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>