config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'sessions/new'

  get 'user/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'signup' => 'users#new'

  resources :posts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end

  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

   root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
The <%= link_to "Ruby on Rails Tutorial", 'http://ok.org' %> by 
<%= link_to "Michael Hartl", 'http://ok.org'%>
 </small>
 <nav>
  <ul>
   <li><%= link_to "About", '#' %></li>
   <li><%= link_to "Contact", '#' %></li>
   <li><%= link_to "News", 'http://ok.org'%></li>
   </ul>
  </nav>
 </footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Hello app", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", static_pages_help_path %></li>
				<% if logged_in? %>
				<li><%= link_to "Users", users_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
						<%= link_to "Log out", logout_path, method: "delete" %>
					</li>
				</ul>
			</li>
			<% else %>
			<li><%= link_to "Log in", login_path %></li>
			<% end %>
		</ul>
	</nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script scr="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 	<title><%= full_title(yield(:title)) %></title>
 	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
 	<%= csrf_meta_tags %>
 	<%= render 'layouts/shim' %>
 </head>
 <body>
 	<%= render 'layouts/header' %>
 	<div class="container">
 		<% flash.each do |message_type, message| %>
 		   <div class="alert alert-<%= message_type %>"><%= message %></div>
 		   <% end %>
 		<%= yield %>
 		<%= render 'layouts/footer' %>
 		<%= debug(params) if Rails.env.development? %>
 	</div>
 </body>
 </html>